#!/bin/bash

timer=30

printf "For which term ID should classes be created? (Press ENTER or CTL+C to cancel.)\n>>> "
read -t $timer term_id
echo ""

if [ -z "$term_id" ]
then 
	echo "Recieved no response."
	exit 1
fi

cd "${0%/*}"
./make_classchoice.py -t $term_id
